### ISSUE TITLE
Treat Enums as strings?

### ISSUE THREAD

**Issue by gulsharan** [gearz-lab/lambda2js#10]
Hey @masbicudo, thanks for this great library!

I was wondering if there is a way to convert this...

```
x => x.SomeEnumProperty == MyEnum.HelloWorld
```

to this...

```
SomeEnumProperty === 'HelloWorld'
```

instead of this...

```
SomeEnumProperty === 0
```

**Comment by andrerpena** [comment]
@masbicudo , you could use Json.NET's approach, which is adding the possibility of defining conversion attributes. For instance:

```
[JsonConverter(typeof(StringEnumConverter))]
public Gender Gender { get; set; }
```

**Comment by masbicudo** [comment]
@gulsharan Pleased to hear your compliment. I'll take a look asap.

@andrerpena I prefer a fluent-like style, so that even types that are not under control of the developer can be annotated (as in my [Fluent-Json.NET](https://github.com/masbicudo/Fluent-Json.NET) project, or even something simpler). If you like the attribute style, or can advocate in favor of it, I can implement both styles through some kind of interface.

Thoughts?

**Comment by gulsharan** [comment]
@andrerpena @masbicudo Thanks for a quick response on this! 
How about adding a serialization setting to JavaScriptCompileOptions so as to allow a blanket rule to serialize all Enums as strings?

**Comment by andrerpena** [comment]
@masbicudo I can see the value of not poluting the model (in this case the enum) with attributes. Agreed.
@gulsharan, the idea of adding this as a general option seems like a good and easier way to get this done fast. Maybe adding the fluent option @masbicudo mentioned should come next.

**Comment by andrerpena** [comment]
these are just my 2 cents BTW. I don't maintain this repo :smile:

**Comment by masbicudo** [comment]
@andrerpena Maintaining is not a requirement to put in your 2 cents! =D

Well, it seems that C# doesn't like me very much. When it converts an expression comparing with an enum value, it automatically converts the enum to the underlying type, that is `int`.

When you code this:

```
o.Gender == Gender.Female
```

C# converts it to an Expression containing this:

```
o.Gender == 1
```

What this means is that I'll have to use contextual information to determine whether the numeric value is an enum... by knowing that it is being compared with an enum valued expression.

Solving this will create another problem, a minor problem, I think. If the user compares explicitly with a number, like this:

```
o.Gender == 1
```

After the solution is implemented, it will be rendered like this:

```
Gender==="Female"
```

Even though it was an integer value in C#.

**Comment by gulsharan** [comment]
Hmm .. interesting point. I think you can leave the current behavior as default, and give the user an option to choose the alternative (treating enums as strings) using an option in JavaScriptCompileOptions. This will go in line with the .Net Web API's Json serialization that defaults to serializing Enums as integers, and you have to explicitly set the JsonSerializerSettings if you wish to serialize them as strings instead.

[http://stackoverflow.com/questions/20242035/mediatypeformatter-serialize-enum-string-values-in-web-api](url)

**Comment by masbicudo** [comment]
I'm back... did some changes in the project, and now converting enum-values to strings is possible, but edge cases may exist because of how C# converts lambda expressions to expression trees.

Sample code:

```
Expression<Func<SomeFlagsEnum>> expr = () => SomeFlagsEnum.A;
var js = expr.CompileToJavascript(
    new JavascriptCompilationOptions(
        JsCompilationFlags.BodyOnly,
        new EnumConversionExtension(EnumOptions.UseStrings)));
```

More samples can be found in the tests file:

https://github.com/gearz-lab/lambda2js/blob/ee29d7af0364d5b34b0cc3b174ad2cce6b44de70/Lambda2Js.Tests/EnumTests.cs

**Comment by gulsharan** [comment]
@masbicudo Thanks for such a comprehensive solution! I'll give it a try tomorrow. :)
