### ISSUE TITLE
Can't handle basic consts??

### ISSUE THREAD

**Issue by i00** [gearz-lab/lambda2js#21]
I have the expression:
```
Expressions.Expression<Func<string, bool>> asd = x => x == "qwe";
Console.WriteLine(asd.CompileToJavascript());
```
This throws an NotSupportedException:
"The used constant value is not supported: `False` (Boolean)"

Kris

**Comment by aviv86** [comment]
@i00 You can use an extention class that inherits from JavascriptConversionExtension and overrides the ConvertToJavascript(JavascriptConversionContext context) method,
then pass it as an argument to CompileToJavascript :

```
asd.CompileToJavascript(new JavascriptCompilationOptions(new ConstSupport()));
```

where ConstSupport extention is something like:

```
public class ConstSupport : JavascriptConversionExtension
{
	public override void ConvertToJavascript(JavascriptConversionContext context)
	{
		if (!(context.Node is ConstantExpression nodeAsConst))
			return;

		var writer = context.GetWriter();
		using (writer.Operation(nodeAsConst))
		{
			if (nodeAsConst.Type == typeof(bool))
			{
				context.PreventDefault();

				var val = (bool)nodeAsConst.Value ? "true" : "false";
				writer.Write(val);	
			
				return;
			}

			if (nodeAsConst.Type == typeof(char))
			{
				context.PreventDefault();

				writer.Write("\"");
				writer.Write(nodeAsConst.Value);
				writer.Write("\"");

				return;

			}
		}
	}
}
```
Aviv

**Comment by masbicudo** [comment]
Hi @i00 and @aviv86 

@i00 Indeed this is a problem. I think that basic literal types should be covered by default. Just like strings and numeric types. I'll fix this and try to find other constant types that are not yet supported.

@aviv86 , thanks for answering.

In the case of `bool` I think it should be supported by default, because the value can be directly mapped to JavaScript.

Not so sure about `char`... in my tests, when chars are treated as numbers in a C# lambda expression, constant char values are given already as `int`, and char variables are cast to int. When char is treated as a string, for example in a string concatenation, constant or variable, it is implicitly converted to `object` by C#.

```
Expression<Func<char, int>> expr1 = (x) => x + 'a'; // x => (Convert(x, Int32) + 97)
Expression<Func<string, string>> expr1 = (x) => x + 'a'; // x => (x + Convert(a, Object))
```

Converting something to two different things, depending on context is confusing... but I lose the "it works out of the box". Maybe it's better to make it work out of the box, even if someone gets confused.

Any thoughts on this?

**Comment by aviv86** [comment]
Hi @masbicudo 

Sure, I agree that booleans should be supported by default.

And I also think that constant chars should be supported by default.
You're right, it's a bit confusing.. but like you said - better to make it work out of the box, even if someone gets confused :)

Actually, I think that the confusing part is that C# implicitly converts them to ints or objects depending on the context, but there won't be anything confusing in Lambda2Js if it will translate constant char values to their string representation.
But maybe I'm missing something..

If constant char values or char variables are treated as ints, then the code in ConstSupport that deals with chars won't affect them at all.
Like in your first example:  
```
Expression<Func<char, int>> expr1 = (x) => x + 'a'; // x => (Convert(x, Int32) + 97)
```
that translates to:
// x => x + 97

And when a char constant is treated as a string and is implicitly converted to object,
like in your second example :
```
Expression<Func<string, string>> expr1 = (x) => x + 'a'; // x => (x + Convert(a, Object))
```
Then the code in ConstSupport will translate it to it's string representation :
// x => (x + Convert(a, Object))
// x => (x + a)
// x => x + 'a'

instead of throwing 
```
System.NotSupportedException: 'The used constant value is not supported: `a` (Char)' .
```

And of course, it will allow you to support expressions with char constants being treated as chars:
```
Expression<Func<object, char>> expr1 = (x) => 'a';
```

BTW,
You can take a look at our Lambda2Js Extentions in RavenDB:
https://github.com/ravendb/ravendb/blob/v4.0/src/Raven.Client/Util/JavascriptConversionExtensions.cs#L1282
we have other constant types that we support via extensions, and also DateTime support, some String methods support, Linq methods supprt, etc.
Would be awesome if some of it will be supported by default :)

Aviv

**Comment by masbicudo** [comment]
Hi @aviv86 and @i00 ,

I have made changes to support these constant literals out of the box,
and uploaded NuGet packages: signed and unsigned.

Thanks for contributing!
